//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalPlace.Domain.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalPlace.Domain.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role key has not a compatible format with a GUID.
        /// </summary>
        public static string Authorization_AssignRole_The_role_key_has_not_a_compatible_format_with_a_GUID {
            get {
                return ResourceManager.GetString("Authorization_AssignRole_The_role_key_has_not_a_compatible_format_with_a_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string CommentsStateType_Accepted {
            get {
                return ResourceManager.GetString("CommentsStateType_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string CommentsStateType_Created {
            get {
                return ResourceManager.GetString("CommentsStateType_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string CommentsStateType_Rejected {
            get {
                return ResourceManager.GetString("CommentsStateType_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acres (ac).
        /// </summary>
        public static string MeasureUnit_Acres {
            get {
                return ResourceManager.GetString("MeasureUnit_Acres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hectares (ha).
        /// </summary>
        public static string MeasureUnit_Hectares {
            get {
                return ResourceManager.GetString("MeasureUnit_Hectares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Feet (ft2).
        /// </summary>
        public static string MeasureUnit_SquareFeet {
            get {
                return ResourceManager.GetString("MeasureUnit_SquareFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Kilometers (km2).
        /// </summary>
        public static string MeasureUnit_SquareKilometers {
            get {
                return ResourceManager.GetString("MeasureUnit_SquareKilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Meters (m2).
        /// </summary>
        public static string MeasureUnit_SquareMeters {
            get {
                return ResourceManager.GetString("MeasureUnit_SquareMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Miles (mi2).
        /// </summary>
        public static string MeasureUnit_SquareMiles {
            get {
                return ResourceManager.GetString("MeasureUnit_SquareMiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SquareYards (yd2).
        /// </summary>
        public static string MeasureUnit_SquareYards {
            get {
                return ResourceManager.GetString("MeasureUnit_SquareYards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In analysis.
        /// </summary>
        public static string RealtyStateType_Analysys {
            get {
                return ResourceManager.GetString("RealtyStateType_Analysys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string RealtyStateType_Created {
            get {
                return ResourceManager.GetString("RealtyStateType_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string RealtyStateType_Published {
            get {
                return ResourceManager.GetString("RealtyStateType_Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string UnitStateType_Active {
            get {
                return ResourceManager.GetString("UnitStateType_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string UnitStateType_Inactive {
            get {
                return ResourceManager.GetString("UnitStateType_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string UserStateType_Active {
            get {
                return ResourceManager.GetString("UserStateType_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string UserStateType_Blocked {
            get {
                return ResourceManager.GetString("UserStateType_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string UserStateType_Created {
            get {
                return ResourceManager.GetString("UserStateType_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string UserStateType_Inactive {
            get {
                return ResourceManager.GetString("UserStateType_Inactive", resourceCulture);
            }
        }
    }
}
